FROM alpine:3.19

# Install small web server
# RUN apk add --no-cache busybox-extras
#
# EXPOSE 80
#
# # Correct CMD
# CMD sh -c 'while true; do echo -e "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nHello World from Docker container!" | nc -l -p 80; done'
